const MOVIE_DB_IMAGE_BASE_URL = process.env.REACT_APP_MOVIE_DB_IMAGE_BASE_URL;
const MOVIE_DB_GENRE_URL = process.env.REACT_APP_MOVIE_DB_GENRE_URL;
const MOVIE_DB_DISCOVER_URL = process.env.REACT_APP_MOVIE_DB_DISCOVER_URL;
const MOVIE_DB_API_URL = process.env.REACT_APP_MOVIE_DB_API_URL;

export {
  MOVIE_DB_IMAGE_BASE_URL,
  MOVIE_DB_GENRE_URL,
  MOVIE_DB_DISCOVER_URL,
  MOVIE_DB_API_URL,
};
